### ISSUE TITLE
Score Version Dependence [BE only]

### ISSUE THREAD

**Issue by BellJrDev** [Collaborative-SWE-at-Purdue/Registry#39]
## Task Information
Score Version Dependence

The VersionDependence score comes from the following: 
The fraction of dependencies that are pinned to at least a specific major+minor version
- A package with 0 dependencies gets a score of 1
- A package with 2 dependencies, one of which is constrained to a minor+major version (eg 2.3.X) gets a ½ = 0.5 score
  
**Notes**
- You are responsible for interfacing with the ModEval Provider which wrapped over the inherited code from Octavo. Ensure that your solution is encapsulated and flows with the rest of the ModEval smoothly, not breaking anything or otherwise upsetting the subsystem. ModEval is already fitted with some space and configuration settings for your addition

**Comment by BellJrDev** [comment]
![Image](https://github.com/user-attachments/assets/69a60368-9de6-409d-bf32-d5fe27a89cca)

**Comment by BellJrDev** [comment]
![Image](https://github.com/user-attachments/assets/67803cab-68f4-4faf-9b95-38dee05a8036)

**Comment by BellJrDev** [comment]
![Image](https://github.com/user-attachments/assets/fa933ebb-5bf7-4473-a87e-f5d53b4cca74)

**Comment by bkanter-purdue** [comment]
Currently have the function in the Evaluator class, since it seemed to make the most sense to put it there with the rest of the scores. 

Figuring out how to start testing. Can change where it is put since it is a pretty easy function.
