### ISSUE TITLE
Score PR-Merge Control [BE only]

### ISSUE THREAD

**Issue by BellJrDev** [Collaborative-SWE-at-Purdue/Registry#40]
## Task Information
Score PR-Merge Control

The PRMergeControl score comes from the following: 
The fraction of project code that was introduced through pull requests with a code review

  
**Notes**
- You are responsible for interfacing with the ModEval Provider which wrapped over the inherited code from Octavo. Ensure that your solution is encapsulated and flows with the rest of the ModEval smoothly, not breaking anything or otherwise upsetting the subsystem. ModEval is already fitted with some space and configuration settings for your addition

**Comment by BellJrDev** [comment]
![Image](https://github.com/user-attachments/assets/0678c9e4-c7c2-42e0-ada7-a9fd9ce4317c)

![Image](https://github.com/user-attachments/assets/69915bf8-4b74-4b5c-a265-c91e096c5fa8)

**Comment by BellJrDev** [comment]
![Image](https://github.com/user-attachments/assets/ee4e844a-2ccd-4e1d-aba6-845651896ad7)

![Image](https://github.com/user-attachments/assets/ca90da22-9bcb-44b1-9fa4-38506fcc68cd)

**Comment by anbates** [comment]
addressed in PR #95
