### ISSUE TITLE
[FE] Update Users w/ Distinct Roles

### ISSUE THREAD

**Issue by BellJrDev** [Collaborative-SWE-at-Purdue/Registry#52]
## **Feature Information**
Allow certain user info to be updated in the database, based on Role.
- Any user should be able to update herself
- An admin should be able to update anyone
=

## Subtasks
**Backend** 
[ ] Create appropriate classes
[ ] Add functionality
[ ] Limit functionality by Role

**Comment by bkanter-purdue** [comment]
@j-leidy If you need any assistance with this part, I have some light HTML/CSS experience. Know you have been given a lot on the front-end, and this seems like somewhere I can help with if need be.

**Comment by j-leidy** [comment]
There is nothing in the spec that statues a user or admin should be able to update user information from what I see. However currently admins can in this upcoming PR. Which is extra from what is in the spec.
