### ISSUE TITLE
[FE] Delete Users w/ Distinct Roles

### ISSUE THREAD

**Issue by BellJrDev** [Collaborative-SWE-at-Purdue/Registry#6]
## Feature Description
Allow users to be removed from the database, based on Role.
- Any user should be able to delete herself
- An admin should be able to delete anyone

## Subtasks
**Backend** 
[ ] Create appropriate classes
[ ] Add functionality
[ ] Limit functionality by Role

**Comment by j-leidy** [comment]
I don't see any way to delete a user on the FE

**Comment by j-leidy** [comment]
Will need some admin page that allows for registration, deletion, updates etc
