### ISSUE TITLE
Authenticate Users With User/Pass [FE]

### ISSUE THREAD

**Issue by BellJrDev** [Collaborative-SWE-at-Purdue/Registry#8]
## Feature Description
Block access to the system with user authentication based on username-password combo and distinct USD permissions

**Notes**
USD = Upload/Search/Download

## Subtasks
**Frontend** 
[ ] Prompt all users for user/pass combo prior to access
[ ] Call for a database query upon receipt of user info
[ ] Block or allow access based on authentication results

**Comment by BellJrDev** [comment]
I was thinking that **this issue included enabling users to log in with credentials stored in the db.**
If that is NOT the case, a new feature will need to be added to the PB to care for this.  I will assign it to @j-leidy.

If that IS correct, then there is an bug, and this issue should remain open until it is resolved.
(2 known username/password combos do not allow successful logging in)

**Comment by j-leidy** [comment]
this is for a user logging in.
Adding, deleting, updating users is something else

**Comment by j-leidy** [comment]
completed
